//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp_LogIn_DotNet_EntityFramework_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userid { get; set; }
        public string usename { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string dateOfBirth { get; set; }
        public string imagePath { get; set; }
    }
}
